version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: redash
    path: client/app
    text-resources:
      - path: "*.tsx"
        format: react-hardcoded
